android:
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: armv7-linux-androideabi, aarch64-linux-android

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android Licenses
      run: yes | sdkmanager --licenses

    - name: Install frontend dependencies
      run: npm i -g pnpm && pnpm install

    - name: Init and build Tauri Android
      env:
        TAURI_ANDROID_TARGET: aarch64-linux-android
        JAVA_HOME: /usr/lib/jvm/default-java
      run: |
        rustup target add aarch64-linux-android
        pnpm tauri android build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: src-tauri/gen/android/**/*.apk
